### ISSUE TITLE
Screenshot is being taken even when screenshot_on_failure = false

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-ruby#35]
**Expected behavior**
In the `reports.properties` of the `gauge-tests ci-ruby` if `screenshot_on_failure = false` then screen shot should not be taken. 

**Actual behavior**
The screen shot should not be taken irrespective of `screenshot_on_failure = false`

**Version**

```
Gauge version: 0.6.2.nightly-2016-08-04

Plugins
-------
csharp (0.9.1.nightly-2016-07-25)
html-report (2.2.0.nightly-2016-08-10)
java (0.5.1.nightly-2016-07-25)
ruby (0.3.1.nightly-2016-07-25)
```

**Comment by kaustavdm** [comment]
Fix should be available in nightly >= 2016-08-22.

**Comment by sguptatw** [comment]
The nightly is not available on 23-08-2016. Please look into the build pipeline.

**Comment by kaustavdm** [comment]
Pipeline has been fixed. [0.3.2.nightly-2016-08-22](https://bintray.com/gauge/gauge-ruby/Nightly/0.3.2.nightly-2016-08-22) is out.

**Comment by sguptatw** [comment]
@kaustavdm : The issue is still replicable in
```
Gauge version: 0.6.2.nightly-2016-08-05

Plugins
-------
csharp (0.9.1.nightly-2016-07-25)
html-report (2.2.0.nightly-2016-08-15)
java (0.5.1.nightly-2016-08-18)
ruby (0.3.2.nightly-2016-08-22)
```

Try gauge-tests where the step `Execute the current project and ensure failure` is used.

**Comment by kaustavdm** [comment]
@sguptatw I tested on latest `ruby 0.3.2.nightly-2016-08-22` and it works for me. Also, tests with `Execute the current project and ensure failure` pass in the pipeline.

Can you post the stacktrace of your test run? It may be that your setup is not using the desired version of gauge-ruby gem.

Try running gauge with:

```
$ bundle exec gauge specs/
```

**Comment by sguptatw** [comment]
@kaustavdm : The tests in gauge-tests won't fail for this issue but you will hear the screen shot being taken on the mentioned tests.

**Comment by kaustavdm** [comment]
Regarding `gauge-tests`, the step implementation for [`Execute the current project and ensure failure`](https://github.com/getgauge/gauge-tests/blob/master/src/test/java/com/thoughtworks/gauge/test/implementation/Execution.java#L55-L58) calls [`currentProject.execute()`](https://github.com/getgauge/gauge-tests/blob/master/src/test/java/com/thoughtworks/gauge/test/common/GaugeProject.java#L209-L212), which in turn calls `executeGaugeCommand()` which explicitly sets [`screenshot_on_failure` to `true`](https://github.com/getgauge/gauge-tests/blob/master/src/test/java/com/thoughtworks/gauge/test/common/GaugeProject.java#L283). That would be the reason why our functional tests keep taking screenshots.

**Comment by sriv** [comment]
The functional test pipelines have been fixed a while ago. Is this issue still relevant?

**Comment by sguptatw** [comment]
The issue still persists. This is not related to gauge_tests. 
```
gauge --init ruby
```
set screenshot_on_failure = false
run gauge specs
check html report. It has the screen shot.

**Comment by apoorvam** [comment]
@sguptatw This issue is fixed. You can try with nightly of gauge-ruby plugin >= 16.12.2016. 

Ensure that `gemfile` references to above version of gauge-ruby.
